
media:
  input: rrfashionstore/images
  output: /images

content:
  - name: products
    label: Products
    type: file
    path: rrfashionstore/data/products.json
    format: json
    list: true
    fields:
      - name: id
        label: Product ID
        type: string

      - name: name
        label: Product Name
        type: string

      - name: price
        label: Price
        type: number

      - name: image
        label: Product Image
        type: image

      - name: category
        label: Category
        type: string

      - name: description
        label: Description
        type: text

      - name: newIn
        label: New In
        type: boolean

      - name: soldOut
        label: Sold Out
        type: boolean
        